name: Docker - Build and Push
on:
  push:
    tags:        
      - v1.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Code checkout
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: bittybit/boldictio-backend
          dockerfile: app/Dockerfile
          addLatest: true
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
